# Generated by Django 2.0.4 on 2018-05-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_ingredient_recipe_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='alternative_names',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
